



package main



var runtimeAndDeps = map[string]bool{
	"internal/abi":                     true, 
	"internal/asan":                    true, 
	"internal/bytealg":                 true, 
	"internal/byteorder":               true, 
	"internal/chacha8rand":             true, 
	"internal/coverage/rtcov":          true, 
	"internal/cpu":                     true, 
	"internal/goarch":                  true, 
	"internal/godebugs":                true, 
	"internal/goexperiment":            true, 
	"internal/goos":                    true, 
	"internal/msan":                    true, 
	"internal/profilerecord":           true, 
	"internal/race":                    true, 
	"internal/runtime/atomic":          true, 
	"internal/runtime/cgroup":          true, 
	"internal/runtime/exithook":        true, 
	"internal/runtime/gc":              true, 
	"internal/runtime/gc/scan":         true, 
	"internal/runtime/maps":            true, 
	"internal/runtime/math":            true, 
	"internal/runtime/pprof/label":     true, 
	"internal/runtime/sys":             true, 
	"internal/runtime/syscall/linux":   true, 
	"internal/runtime/syscall/windows": true, 
	"internal/strconv":                 true, 
	"internal/stringslite":             true, 
	"internal/trace/tracev2":           true, 
	"math/bits":                        true, 
	"runtime":                          true, 
	"unsafe":                           true, 
}











var runtimeAndLinknamed = map[string]bool{
	"arena":                         true, 
	"crypto/fips140":                true, 
	"crypto/internal/boring":        true, 
	"crypto/internal/boring/bcache": true, 
	"crypto/internal/fips140":       true, 
	"crypto/internal/sysrand":       true, 
	"crypto/rand":                   true, 
	"crypto/subtle":                 true, 
	"crypto/x509/internal/macos":    true, 
	"internal/bytealg":              true, 
	"internal/coverage/cfile":       true, 
	"internal/cpu":                  true, 
	"internal/godebug":              true, 
	"internal/poll":                 true, 
	"internal/race":                 true, 
	"internal/reflectlite":          true, 
	"internal/runtime/atomic":       true, 
	"internal/runtime/cgroup":       true, 
	"internal/runtime/maps":         true, 
	"internal/sync":                 true, 
	"internal/synctest":             true, 
	"internal/syscall/unix":         true, 
	"internal/syscall/windows":      true, 
	"maps":                          true, 
	"os":                            true, 
	"os/signal":                     true, 
	"plugin":                        true, 
	"reflect":                       true, 
	"runtime":                       true, 
	"runtime/debug":                 true, 
	"runtime/metrics":               true, 
	"runtime/pprof":                 true, 
	"runtime/secret":                true, 
	"runtime/trace":                 true, 
	"sync":                          true, 
	"sync/atomic":                   true, 
	"sync_test":                     true, 
	"syscall":                       true, 
	"syscall/js":                    true, 
	"time":                          true, 
	"unique":                        true, 
	"weak":                          true, 
	
	"net": true,
	
	
	"testing/synctest": true,
}

var compilerIntrinsics = map[string]map[string]bool{
	"crypto/internal/constanttime": {
		"Select":      true, 
		"boolToUint8": true, 
	},
	"internal/runtime/atomic": {
		"And":             true, 
		"And32":           true, 
		"And64":           true, 
		"And8":            true, 
		"Anduintptr":      true, 
		"Cas":             true, 
		"Cas64":           true, 
		"CasRel":          true, 
		"Casint32":        true, 
		"Casint64":        true, 
		"Casp1":           true, 
		"Casuintptr":      true, 
		"Load":            true, 
		"Load64":          true, 
		"Load8":           true, 
		"LoadAcq":         true, 
		"LoadAcq64":       true, 
		"LoadAcquintptr":  true, 
		"Loadint32":       true, 
		"Loadint64":       true, 
		"Loadp":           true, 
		"Loaduint":        true, 
		"Loaduintptr":     true, 
		"Or":              true, 
		"Or32":            true, 
		"Or64":            true, 
		"Or8":             true, 
		"Oruintptr":       true, 
		"Store":           true, 
		"Store64":         true, 
		"Store8":          true, 
		"StoreRel":        true, 
		"StoreRel64":      true, 
		"StoreReluintptr": true, 
		"Storeint32":      true, 
		"Storeint64":      true, 
		"StorepNoWB":      true, 
		"Storeuintptr":    true, 
		"Xadd":            true, 
		"Xadd64":          true, 
		"Xaddint32":       true, 
		"Xaddint64":       true, 
		"Xadduintptr":     true, 
		"Xchg":            true, 
		"Xchg64":          true, 
		"Xchg8":           true, 
		"Xchgint32":       true, 
		"Xchgint64":       true, 
		"Xchguintptr":     true, 
	},
	"internal/runtime/maps": {
		"bitsetFirst":                  true, 
		"bitsetLowestSet":              true, 
		"bitsetRemoveBelow":            true, 
		"bitsetShiftOutLowest":         true, 
		"ctrlGroupMatchEmpty":          true, 
		"ctrlGroupMatchEmptyOrDeleted": true, 
		"ctrlGroupMatchFull":           true, 
		"ctrlGroupMatchH2":             true, 
	},
	"internal/runtime/math": {
		"Add64":      true, 
		"Mul64":      true, 
		"MulUintptr": true, 
	},
	"internal/runtime/sys": {
		"Bswap32":          true, 
		"Bswap64":          true, 
		"GetCallerPC":      true, 
		"GetCallerSP":      true, 
		"GetClosurePtr":    true, 
		"Len64":            true, 
		"Len8":             true, 
		"OnesCount64":      true, 
		"Prefetch":         true, 
		"PrefetchStreamed": true, 
		"TrailingZeros32":  true, 
		"TrailingZeros64":  true, 
		"TrailingZeros8":   true, 
	},
	"math": {
		"Abs":         true, 
		"Ceil":        true, 
		"Copysign":    true, 
		"FMA":         true, 
		"Floor":       true, 
		"Round":       true, 
		"RoundToEven": true, 
		"Trunc":       true, 
		"sqrt":        true, 
	},
	"math/big": {
		"mulWW": true, 
	},
	"math/bits": {
		"Add":             true, 
		"Add64":           true, 
		"Div":             true, 
		"Div64":           true, 
		"Len":             true, 
		"Len16":           true, 
		"Len32":           true, 
		"Len64":           true, 
		"Len8":            true, 
		"Mul":             true, 
		"Mul64":           true, 
		"OnesCount":       true, 
		"OnesCount16":     true, 
		"OnesCount32":     true, 
		"OnesCount64":     true, 
		"OnesCount8":      true, 
		"Reverse":         true, 
		"Reverse16":       true, 
		"Reverse32":       true, 
		"Reverse64":       true, 
		"Reverse8":        true, 
		"ReverseBytes16":  true, 
		"ReverseBytes32":  true, 
		"ReverseBytes64":  true, 
		"RotateLeft":      true, 
		"RotateLeft16":    true, 
		"RotateLeft32":    true, 
		"RotateLeft64":    true, 
		"RotateLeft8":     true, 
		"Sub":             true, 
		"Sub64":           true, 
		"TrailingZeros16": true, 
		"TrailingZeros32": true, 
		"TrailingZeros64": true, 
		"TrailingZeros8":  true, 
	},
	"runtime": {
		"KeepAlive":            true, 
		"memequal":             true, 
		"publicationBarrier":   true, 
		"slicebytetostringtmp": true, 
	},
	"sync": {
		"runtime_LoadAcquintptr":  true, 
		"runtime_StoreReluintptr": true, 
	},
	"sync/atomic": {
		"AddInt32":              true, 
		"AddInt64":              true, 
		"AddUint32":             true, 
		"AddUint64":             true, 
		"AddUintptr":            true, 
		"AndInt32":              true, 
		"AndInt64":              true, 
		"AndUint32":             true, 
		"AndUint64":             true, 
		"AndUintptr":            true, 
		"CompareAndSwapInt32":   true, 
		"CompareAndSwapInt64":   true, 
		"CompareAndSwapUint32":  true, 
		"CompareAndSwapUint64":  true, 
		"CompareAndSwapUintptr": true, 
		"LoadInt32":             true, 
		"LoadInt64":             true, 
		"LoadPointer":           true, 
		"LoadUint32":            true, 
		"LoadUint64":            true, 
		"LoadUintptr":           true, 
		"OrInt32":               true, 
		"OrInt64":               true, 
		"OrUint32":              true, 
		"OrUint64":              true, 
		"OrUintptr":             true, 
		"StoreInt32":            true, 
		"StoreInt64":            true, 
		"StoreUint32":           true, 
		"StoreUint64":           true, 
		"StoreUintptr":          true, 
		"SwapInt32":             true, 
		"SwapInt64":             true, 
		"SwapUint32":            true, 
		"SwapUint64":            true, 
		"SwapUintptr":           true, 
	},
}

var reflectSkipPkg = map[string]bool{
	"fmt": true,
}
